packages/frontend/src/App.tsx
packages/frontend/src/global.ts
packages/frontend/src/pages/gallery/index.tsx
packages/frontend/src/pages/gallery/search/index.tsx
packages/visual-insights/src/specification.ts

Reason:
1. current search page is actually an easy fuze search based on answer space generated in gallery.
2. gallery and fuze search page can share computed values or state.
3. "real search page" should be developed in future as a NLP query interface. The answer space should use some params extracted from the user query to specify a much clear intend.
others:
fix some warnings.

fix: merge search page into gallery

---

packages/frontend/package.json
packages/frontend/src/pages/visualInterface/index.tsx
packages/graphic-walker/README.md
packages/graphic-walker/package.json
packages/graphic-walker/src/App.tsx
packages/graphic-walker/src/Fields/AestheticFields.tsx
packages/graphic-walker/src/Fields/DatasetFields.tsx
packages/graphic-walker/src/Fields/fieldsContext.tsx
packages/graphic-walker/src/Fields/posFields.tsx
packages/graphic-walker/src/components/clickMenu.tsx
packages/graphic-walker/src/components/container.tsx
packages/graphic-walker/src/components/dataTypeIcon.tsx
packages/graphic-walker/src/components/modal.tsx
packages/graphic-walker/src/config.ts
packages/graphic-walker/src/dataSource/index.tsx
packages/graphic-walker/src/dataSource/pannel.tsx
packages/graphic-walker/src/dataSource/table.tsx
packages/graphic-walker/src/dataSource/utils.ts
packages/graphic-walker/src/utils/index.ts
packages/graphic-walker/src/utils/normalization.ts
packages/graphic-walker/src/vis/future-react-vega.tsx
packages/graphic-walker/src/vis/react-vega.tsx
yarn.lock

feats:
1. hack for facet and repeat cases.
2. fields list order
fixes: dnd drag-id bugs

feat: graphic walker better renderer

---

packages/connectors/app-config.default.json
packages/connectors/app-config.json
packages/connectors/app/controllers/clickHouseProxy.ts
packages/connectors/app/controllers/connection.ts
packages/connectors/app/interfaces.ts
packages/connectors/app/router.ts
packages/connectors/app/store.ts
packages/rath-client/src/components/connectionStatus.tsx
packages/rath-client/src/constants.ts
packages/rath-client/src/interfaces.ts
packages/rath-client/src/pages/dataSource/selection/airtable/index.tsx
packages/rath-client/src/pages/dataSource/selection/clickhouse.tsx
packages/rath-client/src/pages/megaAutomation/narrative/index.tsx
packages/rath-client/src/store/clickhouseStore.ts
packages/rath-client/src/store/pipeLineStore/lts.ts

feat: clickhouse more custom config

---

packages/rath-client/src/pages/dataSource/selection/database/api.ts

Change default connector server path prefix to
-> `https://data-service.kanaries.net/connector`

fix(rath_client): change default connector server host

---

packages/rath-client/package.json
yarn.lock

upgrade: loa for matmic bug

---

packages/rath-client/public/locales/en-US.json
packages/rath-client/public/locales/zh-CN.json
packages/rath-client/src/App.tsx
packages/rath-client/src/components/userSettings.tsx
packages/rath-client/src/components/vizOperationBar.tsx
packages/rath-client/src/constants.ts
packages/rath-client/src/pages/dataSource/selection/local.tsx
packages/rath-client/src/pages/dataSource/settings.tsx
packages/rath-client/src/pages/globalConfig/analysisSettings.tsx
packages/rath-client/src/pages/globalConfig/index.tsx
packages/rath-client/src/pages/globalConfig/megaAutoSetting.tsx
packages/rath-client/src/pages/globalConfig/semiAutoSettings.tsx
packages/rath-client/src/pages/semiAutomation/settings.tsx
packages/rath-client/src/store/commonStore.ts
packages/rath-client/src/store/megaAutomation.ts
packages/rath-client/src/store/semiAutomation/mainStore.ts
packages/rath-client/src/utils/storage.ts

[feat] Global Config Page

---

services/causal-service/Dockerfile
services/causal-service/algorithms/FuncDepTest.py
services/causal-service/algorithms/causallearn/PC.py
services/causal-service/algorithms/causallearn/XLearner.py
services/causal-service/algorithms/common.py
services/causal-service/algorithms/dowhy/ExplainData.py
services/causal-service/main.py
services/causal-service/run-docker.sh

- fix:(WorkAround) display unstable algorithm on dev mode only
- fix:(WorkAround)standardize significance value
- fix:different CORS with dev and prod mode
- feat:use mode=dev instead of dev=1
- build
- devops
- use mode=dev instead of dev=1
- rename

feat[causal-service]:(WorkAround) better production build

---

.gitignore
services/prediction/classification/classification.py
services/prediction/main.py
services/prediction/regression/regression.py
services/prediction/transform.py

add some ML regression & classification model for in causal analysis module.
use causal graph to optimize trainning strategy.

Prediction: modeling

---

packages/rath-client/src/components/react-vega.tsx
packages/rath-client/src/pages/causal/exploration/autoVis/vis.tsx
packages/rath-client/src/pages/collection/collectionView/cardView.tsx
packages/rath-client/src/pages/collection/collectionView/listView.tsx
packages/rath-client/src/pages/collection/index.tsx
packages/rath-client/src/pages/dashboard/renderer/components/dashboard-chart.tsx
packages/rath-client/src/pages/dashboard/source-panel.tsx
packages/rath-client/src/pages/loginInfo/setup.tsx
packages/rath-client/src/pages/megaAutomation/association/assCharts.tsx
packages/rath-client/src/pages/megaAutomation/association/index.tsx
packages/rath-client/src/pages/megaAutomation/gallery/index.tsx
packages/rath-client/src/pages/megaAutomation/mainCanvas/index.tsx
packages/rath-client/src/pages/megaAutomation/vizPagination.tsx
packages/rath-client/src/pages/painter/neighborAutoLink/index.tsx
packages/rath-client/src/pages/progressiveDashboard/index.tsx
packages/rath-client/src/pages/semiAutomation/focusZone/mainCanvas.tsx
packages/rath-client/src/pages/semiAutomation/focusZone/miniFloatCanvas.tsx
packages/rath-client/src/pages/semiAutomation/predictZone/featSegment.tsx
packages/rath-client/src/pages/semiAutomation/predictZone/filterSegment.tsx
packages/rath-client/src/pages/semiAutomation/predictZone/neighborSegment.tsx
packages/rath-client/src/pages/semiAutomation/predictZone/pattSegment.tsx
packages/rath-client/src/queries/themes/config.ts
packages/rath-client/src/queries/themes/index.ts
packages/rath-client/src/queries/themes/theme-ggplot2.ts
packages/rath-client/src/queries/themes/theme-googlecharts.ts
packages/rath-client/src/queries/themes/theme-powerbi.ts
packages/rath-client/src/queries/themes/theme-vox.ts
packages/rath-client/src/store/commonStore.ts

Co-Authored-By: Hao Chen <270001151@qq.com>
#126

feat: visualization theme

---

packages/rath-client/src/App.css
packages/rath-client/src/components/borderCard.tsx
packages/rath-client/src/components/card.tsx
packages/rath-client/src/index.tsx
packages/rath-client/src/pages/dataSource/dataTable/headerCell/index.tsx
packages/rath-client/src/pages/dataSource/dataTable/headerCell/liteStatTable.tsx
packages/rath-client/src/pages/dataSource/dataTable/index.tsx
packages/rath-client/src/pages/dataSource/metaView/distChart.tsx
packages/rath-client/src/pages/dataSource/metaView/metaList.tsx
packages/rath-client/src/pages/dataSource/profilingView/fullDistViz.tsx
packages/rath-client/src/pages/dataSource/profilingView/metaDetail.tsx
packages/rath-client/src/theme.ts

Theme upgrade

---

packages/rath-client/public/locales/en-US.json
packages/rath-client/public/locales/zh-CN.json
packages/rath-client/src/lib/textPattern/init.ts
packages/rath-client/src/pages/dataSource/dataTable/headerCell/index.tsx
packages/rath-client/src/pages/dataSource/dataTable/headerCell/statePlaceholder.tsx
packages/rath-client/src/pages/dataSource/dataTable/index.tsx
packages/rath-client/src/pages/dataSource/dataTable/nestPanel.tsx
packages/rath-client/src/pages/dataSource/dataTable/tpRegexEditor.tsx

+ multi text pattern with group by differernt types
+ editable text pattern
+ show source of text pattern field

feat: multi text pattern

---

packages/rath-client/public/locales/en-US.json
packages/rath-client/public/locales/zh-CN.json
packages/rath-client/src/components/image-export-dialog/dialog-form.tsx
packages/rath-client/src/components/image-export-dialog/export-image.ts
packages/rath-client/src/components/image-export-dialog/index.tsx
packages/rath-client/src/components/react-vega.tsx
packages/rath-client/src/constants.ts
packages/rath-client/src/pages/causal/exploration/explainer/diffChart.tsx
packages/rath-client/src/pages/causal/exploration/explainer/explainChart.tsx
packages/rath-client/src/pages/megaAutomation/vizOperation/operationBar.tsx
packages/rath-client/src/pages/semiAutomation/focusZone/index.tsx
packages/rath-client/src/pages/semiAutomation/focusZone/miniFloatCanvas.tsx
packages/rath-client/src/pages/semiAutomation/index.tsx

✅ Customize file name.
✅ Newly supported format: JPEG.
✅ Customize aspect & display ratio. (Higher quality available)
✅ Customize background color of chart.
Fixes #280 
🐛 Removed link to out-dated vega editor.

[Feat] [fix #280] export images with advanced options

---

packages/rath-client/src/pages/loginInfo/design/index.tsx
packages/rath-client/src/pages/loginInfo/index.tsx
packages/rath-client/src/store/commonStore.ts

Bugfix
1. List of themes may not update at time.
2. Cannot synchronize theme configs in custom panel.
3. An error message is unable to close when a dialog e.g. the login dialog is opened.

fix(theme): list of themes may not update at time

---

packages/rath-client/src/components/backupModal/forms/datasetForm.tsx
packages/rath-client/src/components/backupModal/utils.ts
packages/rath-client/src/interfaces.ts
packages/rath-client/src/pages/dataSource/dataTable/headerCell/components/colNameEditor.tsx
packages/rath-client/src/pages/dataSource/dataTable/headerCell/index.tsx
packages/rath-client/src/pages/dataSource/dataTable/headerCell/styles.tsx
packages/rath-client/src/pages/dataSource/dataTable/index.tsx
packages/rath-client/src/pages/dataSource/metaView/metaList.tsx
packages/rath-client/src/pages/dataSource/profilingView/metaDetail.tsx
packages/rath-client/src/store/dataSourceStore.ts
packages/rath-client/src/store/userStore.ts

Incoming features:
* Allow to set and display the description of each field.
* Record the descriptions of the fields and the dataset itself when uploading the dataset to cloud, and possible to get them when reloading the dataset from cloud.

[Feat](datasource): support dataset & field comment

---

services/connector/bp/bp_database.py

It looks like UI is looking for another path in the URL.
Fix for #325

Fixing local connector service

---

packages/rath-client/package.json
packages/rath-client/src/store/dataSourceStore.ts
yarn.lock

+ upgrade graphic-walker
+ fix graphic-walker keep-alive bug
+ fix field name with \n

dep: upgrade gw

---

packages/rath-client/src/pages/semiAutomation/focusZone/miniFloatCanvas.tsx

fix: apply global zeroscale to minifloat vega

fix: apply zeroscale to mini float

---

packages/rath-client/package.json
packages/rath-client/src/pages/causal/exploration/index.tsx
packages/rath-client/src/pages/manualControl/index.tsx
packages/rath-client/src/pages/painter/embedAnalysis.tsx
yarn.lock

update graphic walker version to 0.4.47

feat: update graphic walker version

---

packages/rath-client/package.json
packages/rath-client/src/App.css
packages/rath-client/src/pages/painter/index.tsx
yarn.lock

Fixed the bugs in painter that caused unnessery spec changes and page height.

fix: painter bugs

---

packages/rath-client/package.json
yarn.lock

update graphic walker to 0.4.50

chore: update graphic walker
